# Generated by Django 5.2.7 on 2026-03-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_currency_alter_payment_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('PROCESS', 'Processed'), ('COMPLETE', 'Completed'), ('FAIL', 'Failed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='entity_type',
            field=models.CharField(choices=[('REFUND', 'Refund'), ('REVERSAL', 'Reversal'), ('PAYMENT', 'Payment'), ('STUDENT', 'Student'), ('USER', 'User')], max_length=20),
        ),
    ]
