# Generated by Django 5.2.7 on 2026-03-21 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_userrole'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('PROCESS', 'Processed'), ('COMPLETE', 'Completed'), ('FAIL', 'Failed')], max_length=20)),
                ('entity_type', models.CharField(choices=[('REFUND', 'Refund'), ('REVERSAL', 'Reversal')], max_length=20)),
                ('entity_id', models.IntegerField()),
                ('old_values', models.JSONField(default=dict)),
                ('new_values', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MultiCurrencyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('converted_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate_used', models.DecimalField(decimal_places=6, max_digits=10)),
                ('exchange_rate_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='converted_payments', to='finance.currency')),
                ('original_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='multi_currency', to='finance.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PAYMENT_CONFIRMATION', 'Payment Confirmation'), ('OUTSTANDING_FEES', 'Outstanding Fees Alert'), ('REPORT_GENERATED', 'Report Generated'), ('SYSTEM_ALERT', 'System Alert')], max_length=30)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('IN_APP', 'In-App')], default='SMS', max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_sms', models.BooleanField(default=True)),
                ('payment_email', models.BooleanField(default=True)),
                ('outstanding_fees_email', models.BooleanField(default=True)),
                ('weekly_summary_email', models.BooleanField(default=False)),
                ('report_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('predicted_daily_collection', models.DecimalField(decimal_places=2, max_digits=10)),
                ('predicted_cumulative', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confidence_level', models.FloatField()),
                ('based_on_days', models.IntegerField(help_text='Number of historical days used for forecast')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.term')),
            ],
            options={
                'ordering': ['-forecast_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REVERSED', 'Reversed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('original_receipt', models.CharField(max_length=100)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('reversed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_reversals', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='finance.payment')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('DUPLICATE', 'Duplicate Payment'), ('OVERPAYMENT', 'Overpayment'), ('PAYMENT_ERROR', 'Payment Error'), ('STUDENT_REQUEST', 'Student Request'), ('POLICY', 'School Policy'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('refund_method', models.CharField(choices=[('BANK_TRANSFER', 'Bank Transfer'), ('MOBILE_MONEY', 'Mobile Money'), ('CASH', 'Cash'), ('CREDIT', 'Account Credit')], max_length=20)),
                ('refund_destination', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.payment')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_email', models.EmailField(blank=True, max_length=254)),
                ('notification_type', models.CharField(choices=[('INITIATION', 'Refund Initiated'), ('APPROVAL', 'Refund Approved'), ('COMPLETION', 'Refund Completed'), ('REJECTION', 'Refund Rejected')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='finance.refund')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('selected_fields', models.JSONField(default=list, help_text='List of fields to include in report')),
                ('filters', models.JSONField(default=dict, help_text='Report filters (class_level, payment_status, date_range)')),
                ('sort_by', models.CharField(default='student_name', max_length=50)),
                ('sort_order', models.CharField(choices=[('asc', 'Ascending'), ('desc', 'Descending')], default='asc', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('report_type', models.CharField(choices=[('COLLECTION_SUMMARY', 'Collection Summary'), ('STUDENT_STATEMENTS', 'Student Statements'), ('PAYMENT_TRANSACTIONS', 'Payment Transactions'), ('COLLECTION_ANALYTICS', 'Collection Analytics'), ('OUTSTANDING_FEES', 'Outstanding Fees'), ('BUDGET_VS_ACTUAL', 'Budget vs Actual')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('email_recipients', models.TextField(help_text='Comma-separated emails')),
                ('include_charts', models.BooleanField(default=True)),
                ('include_summary', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly')], max_length=20)),
                ('next_run', models.DateTimeField()),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='finance.reporttemplate')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.term')),
            ],
            options={
                'ordering': ['-next_run'],
            },
        ),
        migrations.CreateModel(
            name='ReportExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('GENERATED', 'Generated'), ('EMAILED', 'Emailed'), ('FAILED', 'Failed')], default='GENERATED', max_length=20)),
                ('recipients', models.TextField(help_text='Comma-separated emails that received the report')),
                ('error_message', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('scheduled_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='finance.scheduledreport')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='SchoolCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_for_schools', to='finance.currency')),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_config', to='finance.school')),
                ('supported_currencies', models.ManyToManyField(help_text='Currencies accepted by this school', to='finance.currency')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('date', models.DateField()),
                ('source', models.CharField(blank=True, max_length=100)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='finance.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='finance.currency')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PaymentAnalytic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_payments_day', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_count_day', models.IntegerField(default=0)),
                ('average_payment_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_collected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_outstanding', models.DecimalField(decimal_places=2, max_digits=12)),
                ('collection_rate', models.FloatField(default=0)),
                ('cash_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bank_transfer_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cheque_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mobile_money_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('students_paid', models.IntegerField(default=0)),
                ('students_partial', models.IntegerField(default=0)),
                ('students_unpaid', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.term')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('school', 'term', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PaymentMethodTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('MOBILE_MONEY', 'Mobile Money')], max_length=20)),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_count', models.IntegerField()),
                ('percentage_of_total', models.FloatField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.term')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('school', 'term', 'date', 'payment_method')},
            },
        ),
    ]
