# Generated by Django 5.2.7 on 2026-04-04 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_auditlog_action_alter_auditlog_entity_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_date', models.DateField()),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.FileField(upload_to='bank_statements/')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('PROCESSING', 'Processing'), ('RECONCILED', 'Fully Reconciled'), ('PARTIAL', 'Partially Reconciled'), ('FAILED', 'Reconciliation Failed')], default='PENDING', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='finance.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_statements', to='finance.term')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_date'],
            },
        ),
        migrations.CreateModel(
            name='ParentMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('PARENT', 'Parent'), ('SCHOOL', 'School')], max_length=10)),
                ('message_type', models.CharField(choices=[('GENERAL', 'General Inquiry'), ('FEES', 'Fees Related'), ('PAYMENT', 'Payment Issue'), ('STUDENT', 'Student Related'), ('OTHER', 'Other')], default='GENERAL', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('UNREAD', 'Unread'), ('READ', 'Read'), ('REPLIED', 'Replied'), ('RESOLVED', 'Resolved')], default='UNREAD', max_length=20)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_messages', to='finance.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('ACKNOWLEDGED', 'Acknowledged'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('sent_via_sms', models.BooleanField(default=True)),
                ('sent_via_email', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_alerts', to='finance.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='finance.term')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_transaction_id', models.CharField(max_length=255, unique=True)),
                ('bank_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank_date', models.DateField()),
                ('bank_reference', models.CharField(blank=True, max_length=255)),
                ('bank_description', models.TextField(blank=True)),
                ('matched_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_difference', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('UNMATCHED', 'Unmatched'), ('MATCHED', 'Matched'), ('MANUAL_MATCHED', 'Manually Matched'), ('DISPUTED', 'Disputed')], default='UNMATCHED', max_length=20)),
                ('confidence_score', models.FloatField(default=0)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='finance.bankstatement')),
                ('matched_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations_matched', to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='finance.payment')),
            ],
            options={
                'ordering': ['-bank_date'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationDiscrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancy_type', models.CharField(choices=[('AMOUNT_MISMATCH', 'Amount Mismatch'), ('DATE_MISMATCH', 'Date Mismatch'), ('MISSING_PAYMENT', 'Missing Payment Record'), ('DUPLICATE_TRANSACTION', 'Duplicate Transaction'), ('UNKNOWN_SENDER', 'Unknown Sender'), ('LATE_DEPOSIT', 'Late Deposit')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('description', models.TextField()),
                ('suggested_action', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='finance.paymentreconciliation')),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
    ]
