# Generated by Django 5.2.7 on 2026-04-04 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_bankstatement_parentmessage_paymentalert_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_type', models.CharField(choices=[('PARENT', 'Parent'), ('STUDENT', 'Student')], default='PARENT', max_length=10)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('message_content', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('SENT', 'Sent Successfully'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('scheduled_send_time', models.DateTimeField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminders', to='finance.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminders', to='finance.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminders', to='finance.term')),
            ],
            options={
                'ordering': ['-scheduled_send_time'],
            },
        ),
        migrations.CreateModel(
            name='SMSReminderConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('trigger_type', models.CharField(choices=[('DAYS_BEFORE', 'Days Before Due Date'), ('OVERDUE', 'Payment Overdue'), ('SPECIFIC_DATE', 'Specific Date')], default='DAYS_BEFORE', max_length=20)),
                ('days_before_due', models.IntegerField(default=3, help_text='Send reminder this many days before due date')),
                ('max_daily_reminders', models.IntegerField(default=500, help_text='Maximum SMS to send per day')),
                ('message_template', models.TextField(default='Dear {student_name}, payment of UGX {amount} for {term_name} is due on {due_date}. Please pay to avoid penalties.', help_text='Use {student_name}, {parent_name}, {amount}, {term_name}, {due_date} as placeholders')),
                ('send_time', models.TimeField(default='08:00', help_text='Time to send reminders (HH:MM format)')),
                ('send_days', models.CharField(default='1,2,3,4,5', help_text='Comma-separated day numbers: 1=Monday, 2=Tuesday, ..., 7=Sunday', max_length=50)),
                ('sms_cost_per_unit', models.DecimalField(decimal_places=2, default=200, help_text='Cost in UGX per SMS', max_digits=8)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sms_reminder_config', to='finance.school')),
            ],
            options={
                'verbose_name_plural': 'SMS Reminder Configurations',
            },
        ),
        migrations.CreateModel(
            name='SMSReminderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_type', models.CharField(choices=[('PARENT', 'Parent'), ('STUDENT', 'Student')], max_length=10)),
                ('message_sent', models.TextField()),
                ('amount_reminded', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sms_gateway_response', models.CharField(default='PENDING', max_length=50)),
                ('gateway_message_id', models.CharField(blank=True, max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, default=200, max_digits=8)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_history', to='finance.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_history', to='finance.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_history', to='finance.term')),
            ],
            options={
                'verbose_name_plural': 'SMS Reminder Histories',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='SMSReminderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('message_template', models.TextField(help_text='Use {student_name}, {parent_name}, {amount}, {term_name}, {due_date} as placeholders')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_templates', to='finance.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
