# Generated by Django 5.2.7 on 2026-04-04 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_smsreminder_smsreminderconfiguration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('PAYMENT_OVERDUE', 'Payment Overdue'), ('BUDGET_EXCEEDED', 'Budget Exceeded'), ('RECONCILIATION_MISMATCH', 'Reconciliation Mismatch'), ('SMS_BUDGET_LOW', 'SMS Budget Low'), ('SYSTEM_ERROR', 'System Error'), ('INFO', 'Information')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('target_role', models.CharField(blank=True, choices=[('BURSAR', 'Bursar'), ('HEADMASTER', 'Headmaster'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent')], max_length=20, null=True)),
                ('action_url', models.CharField(blank=True, max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_alerts', to='finance.school')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboard_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-severity', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('columns', models.IntegerField(default=3, help_text='Number of columns for dashboard grid')),
                ('hidden_widgets', models.JSONField(default=list, help_text='List of widget IDs that user has hidden')),
                ('widget_order', models.JSONField(default=list, help_text='Custom widget ordering')),
                ('show_notifications', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily Digest'), ('weekly', 'Weekly Digest')], default='daily', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='finance.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Dashboard Preferences',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('BURSAR', 'Bursar'), ('HEADMASTER', 'Headmaster'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent')], max_length=20)),
                ('widget_type', models.CharField(choices=[('payment_summary', 'Payment Summary'), ('outstanding_fees', 'Outstanding Fees'), ('recent_payments', 'Recent Payments'), ('class_performance', 'Class Performance'), ('student_roster', 'Student Roster'), ('attendance_overview', 'Attendance Overview'), ('fee_breakdown', 'Fee Breakdown'), ('sms_reminders_stats', 'SMS Reminders Statistics'), ('bank_reconciliation', 'Bank Reconciliation'), ('payment_methods', 'Payment Methods'), ('payment_analytics', 'Payment Analytics'), ('top_students', 'Top Outstanding Students')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Display order on dashboard')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to='finance.school')),
            ],
            options={
                'ordering': ['role', 'order'],
                'unique_together': {('school', 'role', 'widget_type')},
            },
        ),
    ]
