# Generated by Django 6.0.3 on 2026-04-05 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_dashboardalert_dashboardpreference_dashboardwidget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('PAYMENT', 'Payment Recorded'), ('REFUND', 'Refund Processed'), ('STUDENT_CREATED', 'Student Created'), ('STUDENT_UPDATED', 'Student Updated'), ('FEE_UPDATED', 'Fee Updated'), ('SMS_SENT', 'SMS Reminder Sent'), ('TERM_CREATED', 'Term Created'), ('RECONCILIATION', 'Bank Reconciliation'), ('ALERT_GENERATED', 'Payment Alert'), ('USER_LOGIN', 'User Login'), ('REPORT_GENERATED', 'Report Generated'), ('OTHER', 'Other Activity')], max_length=30)),
                ('title', models.CharField(help_text='Short title of the activity', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('visible_to_roles', models.JSONField(default=list, help_text='List of roles that can see this activity (e.g., ["BURSAR", "HEADMASTER"])')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context data as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='finance.payment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='finance.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='finance.student')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', '-created_at'], name='finance_act_school__c03c31_idx'), models.Index(fields=['school', 'activity_type', '-created_at'], name='finance_act_school__f3bc61_idx')],
            },
        ),
    ]
