# Generated by Django 6.0.3 on 2026-04-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='student_id_format',
            field=models.CharField(blank=True, help_text='Example: STU0001, A001, 2024-001. This is for documentation only - actual IDs are entered freely.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('BURSAR', 'Bursar/Admin'), ('HEADMASTER', 'Headmaster'), ('TEACHER', 'Teacher'), ('PARENT', 'Parent')], default='BURSAR', max_length=20),
        ),
    ]
